application.name=bookstore-app
spring.application.name=bookstore-app
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=false
springdoc.enable-spring-security=false

feign.client.config.default.load-balancer-enabled=false

management.endpoints.web.exposure.include=*
management.endpoint.metrics.enabled=true
management.endpoint.beans.enabled=true
management.endpoint.health.probes.enabled=true

management.influx.metrics.export.db=book-metrics-db
management.influx.metrics.export.user-name=admin
management.influx.metrics.export.password=admin
management.influx.metrics.export.uri=http://localhost:8086

otel.metrics.exporter=none
logging.level.io.opentelemetry=DEBUG
logging.level.io.opentelemetry.exporter.zipkin=DEBUG

management.endpoint.health.show-components=always
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0

management.opentelemetry.resource-attributes.application=${spring.application.name}
management.opentelemetry.resource-attributes.cluster=local

management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.exporter=zipkin
otel.traces.exporter=zipkin
otel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans
otel.service.name=bookstore-app
